# Generated by Django 4.2.18 on 2025-02-03 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business_type', models.CharField(blank=True, choices=[('music_academy', 'Music Academy'), ('dance_academy', 'Dance Academy'), ('art_academy', 'Art Academy'), ('sports_academy', 'Sports Academy'), ('coaching_center', 'Coaching Center'), ('fitness_center', 'Gym & Fitness Center'), ('retail', 'Retail'), ('ecommerce', 'E-commerce'), ('technology', 'Technology'), ('finance', 'Finance'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('hospitality', 'Hospitality'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=30, null=True)),
                ('business_owner', models.CharField(blank=True, max_length=100)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_about', models.TextField(blank=True, help_text='Short description about the business', null=True)),
                ('business_address', models.TextField()),
                ('business_phone', models.CharField(max_length=15)),
                ('business_website', models.URLField(blank=True, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, help_text='Year of establishment', null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('business_logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
