# Generated by Django 4.2.18 on 2025-03-11 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_notification_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('no_of_equipment', models.IntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
