# Generated by Django 4.2.18 on 2025-03-11 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_equipmentmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentmaster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='EquipmentMaster/equipment_images/'),
        ),
    ]
