# Generated by Django 4.2.18 on 2025-03-11 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_equipmentmaster_created_by_equipmentmaster_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_awarded', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Achievement/images/')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.businessinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
