# Generated by Django 4.2.18 on 2025-03-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
