# Generated by Django 4.2.18 on 2025-04-01 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_alter_businessinfo_user_alter_personalinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='core_userac_ip_addr_9ed689_idx'), models.Index(fields=['user'], name='core_userac_user_id_471f5d_idx')],
            },
        ),
    ]
