# Generated by Django 4.2.18 on 2025-02-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(upload_to='Post/medias/'),
        ),
    ]
