# Generated by Django 4.2.18 on 2025-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_post_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
