# Generated by Django 4.2.18 on 2025-03-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_category_post_duration_post_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
