# Generated by Django 4.2.18 on 2025-03-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_batch_is_system_subtask_is_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterpolicy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterpolicy',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
